development: &default
  adapter: sqlite3
  database: db/echo_development.sqlite3
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 15)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  reconnect: true

test:
  <<: *default
  database: db/echo_test.sqlite3

production: &prod
  adapter: mysql2
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 15)), Integer(ENV.fetch("DB_POOL", 15))].max %>
  timeout: 5000
  database: echo_production
  username: echo
  password: <%= ENV["MYSQL_PASSWD"] %>
  shost: localhost

staging:
  <<: *prod
  
