development: &default
  adapter: sqlite3
  database: db/echo_development.sqlite3
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: db/echo_test.sqlite3

production: &prod
  adapter: mysql2
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  database: echo_production
  username: echo
  password: <%= ENV["MYSQL_PASSWD"] %>
  shost: localhost

staging:
  <<: *prod
  
